os: linux
compiler: gcc

before_script:
  - svn co 'svn://udo-open-source.org/UDO/trunk /tmp/udo'
  - cd /tmp/udo/Source && make -f Makefile.linux && cd -
  - export PATH=$PATH:/tmp/udo/Source

script:
  - mkdir -p "docs.new/de/bilder" "docs.new/en/bilder"
  - cp -r "bilder/gif" "docs.new/de/bilder"
  - cp -r "bilder/gif" "docs.new/en/bilder"
  - cp "html/tos_hyp.gif" "docs.new"
  - udo --html -o "$PWD/docs.new/index.html" "$PWD/html/tos_hyp.u"
  - udo --html -o "$PWD/docs.new/de/index.html" "$PWD/tos_hyp.u"
  #- udo --html -o "$PWD/docs.new/en/index.html" "$PWD/tos_hyp.u"
  
after_success:
  - git rm -rf "docs"
  - mv "docs.new" "docs"
  - git add "docs" # && git push
